[features]
seeds = false
[programs.localnet]
switchboard_vrf_flip = "FLiPhaxG6sdasFpRoc17u1QKq96g2p2BTNNT1rqXvcnC"
[programs.mainnet]
switchboard_vrf_flip = "FLiPhaxG6sdasFpRoc17u1QKq96g2p2BTNNT1rqXvcnC"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
# cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx mocha --extension ts --require ts-node/register -t 1000000 tests/**/*.test.ts"

[test.validator]
url="https://api.devnet.solana.com"

[test]
startup_wait = 10000

# sbv2 devnet programID
[[testnet.validator.clone]] 
address="2TfB33aLaneQb5TNVwyDz3jSZXS6jdW2ARw1Dgf84XCG"

# sbv2 devnet program data address
[[testnet.validator.clone]] 
address="J4CArpsbrZqu1axqQ4AnrqREs3jwoyA1M5LMiQQmAzB9"

# sbv2 devnet IDL address
[[testnet.validator.clone]]
address="CKwZcshn4XDvhaWVH9EXnk3iu19t6t5xP2Sy2pD6TRDp"

# sbv2 devnet SbState account
[[testnet.validator.clone]]
address="BYM81n8HvTJuqZU1PmTVcwZ9G8uoji7FKM6EaPkwphPt"