# Run the anchor tests against the deployed version of VRF Flip on devnet
name: Devnet Tests

on:
  workflow_dispatch:

jobs:
  vrfFlipTest:
    name: "VRF Flip Devnet Tests"
    runs-on: ubuntu-latest
    timeout-minutes: 25
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        nodeVersion: [18]
    steps:
      - uses: actions/checkout@v3

      - name: Setup Workspace
        uses: ./.github/actions/setup-workspace
        with:
          solanaVersion: "v1.14.10"
          anchorVersion: "0.27.0"
          nodeVersion: ${{ matrix.nodeVersion }}

      - name: Anchor Test
        run:
          anchor test --skip-build --skip-deploy --provider.cluster ${{
          secrets.SOLANA_DEVNET_RPC }}
        env:
          SOLANA_CLUSTER: "devnet"
