name: Localnet Tests
on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - ".github/**"
      - "package.json"
      - "yarn.lock"
      - "tests/**"
      - "programs/vrf-flip/**"
      - "client/**"

jobs:
  vrfFlipTest:
    name: "VRF Flip Localnet Tests"
    runs-on: ubuntu-latest
    timeout-minutes: 25
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        nodeVersion: [18, 19.7]
    steps:
      - uses: actions/checkout@v3

      - name: Setup Workspace
        uses: ./.github/actions/setup-workspace
        with:
          solanaVersion: "v1.14.10"
          anchorVersion: "0.27.0"
          nodeVersion: ${{ matrix.nodeVersion }}

      - name: Anchor Test
        run: anchor test
